name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: youracr.azurecr.io/yourapp:latest

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@v0.5.7
      with:
        image-ref: 'youracr.azurecr.io/yourapp:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true

    - name: Deploy to AKS
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: yourClusterName
        resource-group: yourResourceGroupName
    - name: Kubernetes deployment
      run: |
        kubectl apply -f deployment.yml
        kubectl set image deployment/yourapp-deployment yourapp=youracr.azurecr.io/yourapp:latest
