name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build . -t oztestaks.azurecr.io/myapp:${{ github.sha }}
          az acr login --name oztestaks
          docker push oztestaks.azurecr.io/myapp:${{ github.sha }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: MyFirstCluster
          resource-group: MyResourceGroup

      - name: Deploy to AKS
        run: |
          kubectl apply -f ./k8s/deployment.yml
          kubectl apply -f ./k8s/service.yml

      - name: Scan for security vulnerabilities
        uses: Azure/container-scan@v0
        with:
          image-name: oztestaks.azurecr.io/myapp:${{ github.sha }}
